#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom audio audioSample
#' @importFrom audio play
#' @importFrom dplyr %>%
#' @importFrom dplyr across
#' @importFrom dplyr all_of
#' @importFrom dplyr case_when
#' @importFrom dplyr contains
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr distinct_at
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr select
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarize
#' @importFrom graphics barplot
#' @importFrom graphics grconvertX
#' @importFrom graphics grconvertY
#' @importFrom graphics legend
#' @importFrom graphics lines
#' @importFrom graphics matplot
#' @importFrom graphics par
#' @importFrom graphics polygon
#' @importFrom graphics rect
#' @importFrom graphics symbols
#' @importFrom graphics text
#' @importFrom grDevices xy.coords
#' @importFrom haven read_sas
#' @importFrom MASS eqscplot
#' @importFrom readr read_csv
#' @importFrom rlang :=
#' @importFrom rlang .data
#' @importFrom seriation get_order
#' @importFrom seriation seriate
#' @importFrom shape plotcircle
#' @importFrom shiny a
#' @importFrom shiny clickOpts
#' @importFrom shiny conditionalPanel
#' @importFrom shiny div
#' @importFrom shiny eventReactive
#' @importFrom shiny hoverOpts
#' @importFrom shiny icon
#' @importFrom shiny isolate
#' @importFrom shiny reactive
#' @importFrom shiny reactiveValues
#' @importFrom shiny renderUI
#' @importFrom shiny splitLayout
#' @importFrom shiny uiOutput
#' @importFrom shiny updateSliderInput
#' @importFrom shinyBS bsCollapse
#' @importFrom shinyBS bsCollapsePanel
#' @importFrom shinyBS updateCollapse
#' @importFrom shinyjs click
#' @importFrom shinyjs delay
#' @importFrom shinyjs disable
#' @importFrom shinyjs enable
#' @importFrom shinyjs extendShinyjs
#' @importFrom shinyjs inlineCSS
#' @importFrom shinyjs reset
#' @importFrom shinyjs useShinyjs
#' @importFrom shinyWidgets circleButton
#' @importFrom shinyWidgets knobInput
#' @importFrom shinyWidgets materialSwitch
#' @importFrom shinyWidgets pickerInput
#' @importFrom shinyWidgets radioGroupButtons
#' @importFrom stats aggregate
#' @importFrom stats end
#' @importFrom stats na.omit
#' @importFrom tidyr drop_na
#' @importFrom tidyselect one_of
#' @importFrom utils head
#' @importFrom utils packageVersion
#' @importFrom utils tail
## usethis namespace: end
NULL
